-- DROP ALL TABLES IN USER_TABLES
SET SERVEROUTPUT ON
DECLARE
    TABLE_NAME VARCHAR2(2000);
    CURSOR tables is SELECT * FROM USER_TABLES;
    DRY_RUN BOOLEAN;
BEGIN
    DRY_RUN := FALSE;        -- PLEASE TURN TO FALSE FOR USE!
    FOR t IN tables LOOP
        TABLE_NAME := t.TABLE_NAME;
        IF DRY_RUN = FALSE THEN
            EXECUTE IMMEDIATE 'DROP TABLE ' || TABLE_NAME;
        END IF;
        DBMS_OUTPUT.PUT_LINE(TABLE_NAME || ' has dropped.' || CASE DRY_RUN WHEN TRUE THEN '(DRYRUN)' END);
    END LOOP;
END;
/


